export const theme = {
  colors: {
    primary: '#0194f3',
    primaryDark: '#0066cc',
    accent: '#ff5e1f',
    success: '#4caf50',
    warning: '#ff9800',
    background: '#f5f7f9',
    surface: '#ffffff',
    text: '#1c1c1c',
    textMuted: '#666666',
    border: '#e6e8ee',
    heroGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    primaryGradient: 'linear-gradient(135deg, #0194f3 0%, #0066cc 100%)',
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: '50%',
    '2xl': 24,
    '3xl': 32,
  },
  shadows: {
    sm: '0 4px 12px rgba(0,0,0,0.06)',
    md: '0 10px 25px rgba(0,0,0,0.08)',
    lg: '0 20px 60px rgba(0,0,0,0.18)',
    xl: '0 15px 35px rgba(0,0,0,0.1)',
    '2xl': '0 20px 60px rgba(0,0,0,0.2)',
  },
  fonts: {
    primary: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
  },
  typography: {
    xs: '12px',
    sm: '13px',
    base: '14px',
    lg: '16px',
    xl: '18px',
    '2xl': '20px',
    '3xl': '28px',
    '4xl': '36px',
  },
  fontWeights: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    '2xl': '24px',
    '3xl': '32px',
    '4xl': '40px',
  },
}

export const ui = {
  page: {
    minHeight: '100vh',
    backgroundColor: theme.colors.background,
    fontFamily: theme.fonts.primary,
  },
  card: {
    base: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      boxShadow: theme.shadows.md,
      border: `1px solid ${theme.colors.border}`,
    }
  },
  input: {
    base: {
      padding: '12px',
      borderRadius: theme.radius.md,
      border: `1px solid ${theme.colors.border}`,
      fontSize: theme.typography.sm,
      outline: 'none',
      fontFamily: theme.fonts.primary,
      backgroundColor: theme.colors.surface,
    }
  },
  button: {
    primary: {
      background: theme.colors.primaryGradient,
      color: theme.colors.surface,
      padding: '12px 20px',
      borderRadius: theme.radius.md,
      border: 'none',
      fontWeight: theme.fontWeights.bold,
      fontSize: theme.typography.sm,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing.sm,
      transition: 'all 0.2s',
    },
    secondary: {
      padding: '8px 16px',
      borderRadius: theme.radius.md,
      border: `1px solid ${theme.colors.border}`,
      backgroundColor: 'transparent',
      cursor: 'pointer',
      fontWeight: theme.fontWeights.semibold,
      fontSize: theme.typography.sm,
      color: theme.colors.text,
      transition: 'all 0.2s',
    },
    outline: {
      padding: '8px 16px',
      borderRadius: theme.radius.md,
      border: 'none',
      backgroundColor: `${theme.colors.primary}20`,
      color: theme.colors.primary,
      cursor: 'pointer',
      fontWeight: theme.fontWeights.bold,
      fontSize: theme.typography.sm,
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing.sm,
      transition: 'all 0.2s',
    },
    danger: {
      padding: '6px 10px',
      backgroundColor: `${theme.colors.accent}20`,
      color: theme.colors.accent,
      border: 'none',
      borderRadius: theme.radius.md,
      cursor: 'pointer',
      fontSize: theme.typography.sm,
      transition: 'all 0.2s',
    },
  },
}
